name: "🧑‍🏭"

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Git
        uses: actions/checkout@v2

      - name: Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Package
        run: ./gradlew build --stacktrace

      - name: Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: 'automated release at commit ${{ github.sha }}'
          draft: false
          prerelease: false

      - name: Release
        uses: csexton/release-asset-action@v2
        with:
          pattern: "build/libs/*.jar"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
